import type { FeatureId } from '@/types/features';
import type { RoleId } from '@/types/roles';
import type { AccessLevel } from '@/types/roles';

/**
 * Matriz de Accesos Integrada v4.0
 * 213 funciones × 7 roles = 1,491 celdas de control de acceso
 * Generada desde: MATRIZ-ACCESOS-INTEGRADOS.md
 * Status: Validada 2026-04-23
 */

export const FEATURE_ACCESS_MATRIX: Record<FeatureId, Record<RoleId, AccessLevel>> = {
  // M01: Gestión de Propiedades y Unidades
  tree_hierarchy: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  bulk_property_import: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  unit_classification: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  coefficients_config: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  unit_master_file: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  parking_management: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  visual_property_map: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  multi_condo_enterprise: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  unit_assets_relation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  maintenance_blocking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  unit_blocking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },

  // M02: Gestión de Residentes y Censo
  owner_tenant_authorization: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  resident_history: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  family_nucleus: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  resident_onboarding: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  emergency_contacts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  special_conditions_registry: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  occupancy_traceability: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  universal_linking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  packages_correspondence: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  resident_documents: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M03: Comunicaciones y Comunidad
  read_receipts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  communication_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  library_announcements: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  community_calendar: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  confirmation_reading: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  surveys_polls: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  draft_generation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  comment_moderation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  recurring_communications: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  campaign_scheduling: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  reactions_control: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  digital_voting: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'FULL_ACCESS',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M04: Pagos, Cartera y Recaudo
  payment_agreements: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  morosity_alerts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  payment_blocking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  portfolio_seniority: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  auto_payment_reconciliation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  integrated_receivables: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  account_statements: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  collection_history: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  bank_integration: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  credit_debit_notes: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  progressive_notifications: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  multilevel_payments: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  partial_payments: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  payment_prediction: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  payment_promises: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  extraordinary_collection: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  multichannel_collection: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  payment_restrictions: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  refinancing_simulator: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  commission_system: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  portfolio_board: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  daily_collection_board: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M05: Contabilidad Básica e Integración
  cost_centers: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  assisted_monthly_closing: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  accounting_vouchers: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  reconciliations: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  accounts_payable: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  reference_depreciation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  accounting_exports: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  closing_signature: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  erp_integration: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  budget_comparison: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  budget_execution: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  accounting_traceability: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  closing_validations: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M06: Reservas de Zonas Comunes
  resource_calendar: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  check_in_check_out: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  space_condition_evidence: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  reservation_history: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  waiting_list: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  reservation_deposits: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  non_use_penalties: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  space_policies: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },

  // M07: Gestión de PQRS y Tickets
  trays_by_responsible: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  suggested_responses: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  convivence_committee_flow: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'FULL_ACCESS',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  complaint_patterns: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  recurrence_indicators: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  root_cause_analysis: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  case_reopening: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  escalation_rules: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  pqrs_summary: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  sla_configuration: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  closure_satisfaction: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  sla_semaphores: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  priority_tickets: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  internal_external_tickets: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },

  // M08: Gestión de Mantenimiento y Activos
  services_agenda: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  renewal_alerts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  asset_checklists: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  spare_consumption: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  accumulated_costs: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  before_after_evidence: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'LIMITED',
  },
  asset_technical_data: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  intervention_history: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  preventive_maintenance: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  work_orders: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'FULL_ACCESS',
  },
  maintenance_productivity: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  serials_warranties: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  maintenance_suggestions: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  asset_location: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  expiration_semaphores: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },

  // M09: Seguridad y Control de Acceso
  blocked_unit_alerts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  porteria_bitacora: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  restricted_zone_access: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  delivery_control: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  ingress_evidence: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'LIMITED',
  },
  contractor_ingress: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'LIMITED',
  },
  smart_integration: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  blacklists_alerts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  express_porteria_panel: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  ingress_registry: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'LIMITED',
  },
  security_incidents: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  security_board: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  security_shifts: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  identity_validation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  validation_methods: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  frequent_visitors: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },
  digital_invitations: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'FULL_ACCESS',
    proveedor: 'NONE',
  },

  // M10: Gestión Documental
  folders_by_profile: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  document_consultation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  robust_version_control: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  document_approval_flows: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'FULL_ACCESS',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  resident_documents_mgmt: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  document_ocr: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  document_permissions: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  document_templates: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  institutional_templates: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  document_expiration: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  digital_signature: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'FULL_ACCESS',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M11: Marketplace y Servicios
  paid_campaigns: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  provider_comparison: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  marketplace_commercial_dashboard: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  provider_status: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  provider_evaluation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  leads_management: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  providers_listing: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  segmented_offers: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  verified_reviews: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  quotation_requests: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  service_traceability: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  provider_validation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },

  // M12: Panel del Administrador (Dashboard)
  dashboard_by_role: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  pending_tasks_panel: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  action_recommendations: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  daily_summary: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  configurable_widgets: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M13: Módulo IA Copiloto PH
  anomaly_analysis: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  administrative_assistant: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  resident_chatbot: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  help_chatbot: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  automatic_classification: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  council_copilot: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'FULL_ACCESS',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  profile_copilot: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  pattern_detection: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  ia_explainability: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  draft_communications: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  predictive_indicators: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  contextual_responses: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  maintenance_suggestions_ia: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  contextual_suggestions: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  auto_translation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },

  // M14: Analítica, BI y Reportes
  communications_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  incidents_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  occupation_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  providers_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  spaces_usage_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'LIMITED',
    proveedor: 'NONE',
  },
  controlled_anonymity: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  anomalies_analysis: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  aperture_engagement: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  benchmarks_between_condos: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  historical_comparatives: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  report_builder: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  adoption_indicators: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  operational_heatmap: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  maintenance_productivity_analytics: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  performance_ranking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  risk_ranking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  scheduled_reports: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  advanced_segmentation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  financial_board: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  interaction_traceability: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },

  // M15: Configuración y Parametrización
  module_activation: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  digital_adoption: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  approval_rules: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  branding_by_condo: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  advanced_search: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  semantic_search: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  calendars_holidays: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  categories_subcategories: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  master_catalogs: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  special_hours_config: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  integrations_config: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  max_quotas_user: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  master_states: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  access_delegations: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  feature_flags: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  advanced_filters: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  excel_import: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  metadata_taxonomies: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  multi_language: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  multi_currency: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  approval_levels: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  guided_onboarding: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  visual_personalization: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  preset_templates: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  notification_policies: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },
  visibility_policies: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  configurable_rules: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  auto_translation_config: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'NONE',
    proveedor: 'LIMITED',
  },

  // M16: Soporte, Ayuda y Centro de Conocimiento
  articles_videos: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  knowledge_by_role: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  contextual_help: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  support_chat_tickets: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  admin_training: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'NONE',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  platform_incidents: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  dynamic_faq: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  support_tracking: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'NONE',
    propietario: 'LIMITED',
    arrendatario: 'NONE',
    porteria: 'NONE',
    proveedor: 'NONE',
  },
  product_tours: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'LIMITED',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
  short_videos: {
    super_admin: 'FULL_ACCESS',
    admin: 'FULL_ACCESS',
    consejo: 'READ_ONLY',
    propietario: 'LIMITED',
    arrendatario: 'LIMITED',
    porteria: 'LIMITED',
    proveedor: 'LIMITED',
  },
};

/**
 * Obtiene el nivel de acceso para una función específica por rol
 */
export function getFeatureAccess(
  featureId: FeatureId,
  roleId: RoleId
): AccessLevel {
  return FEATURE_ACCESS_MATRIX[featureId]?.[roleId] ?? 'NONE';
}

/**
 * Verifica si un rol tiene acceso a una función
 */
export function hasFeatureAccess(
  featureId: FeatureId,
  roleId: RoleId,
  minimumLevel: AccessLevel = 'LIMITED'
): boolean {
  const accessLevel = getFeatureAccess(featureId, roleId);
  const levels: AccessLevel[] = ['FULL_ACCESS', 'LIMITED', 'READ_ONLY', 'OWN_DATA_ONLY'];
  const minimumIndex = levels.indexOf(minimumLevel);
  return levels.indexOf(accessLevel) <= minimumIndex && accessLevel !== 'NONE';
}

/**
 * Obtiene todas las funciones accesibles para un rol
 */
export function getFeaturesForRole(roleId: RoleId): FeatureId[] {
  return (Object.entries(FEATURE_ACCESS_MATRIX) as [FeatureId, Record<RoleId, AccessLevel>][])
    .filter(([, accesses]) => accesses[roleId] !== 'NONE')
    .map(([featureId]) => featureId);
}

/**
 * Mapa de referencias cruzadas: Función -> Módulo
 */
export const FEATURE_TO_MODULE: Record<FeatureId, string> = {
  tree_hierarchy: 'M01',
  bulk_property_import: 'M01',
  unit_classification: 'M01',
  coefficients_config: 'M01',
  unit_master_file: 'M01',
  parking_management: 'M01',
  visual_property_map: 'M01',
  multi_condo_enterprise: 'M01',
  unit_assets_relation: 'M01',
  maintenance_blocking: 'M01',
  unit_blocking: 'M01',
  owner_tenant_authorization: 'M02',
  resident_history: 'M02',
  family_nucleus: 'M02',
  resident_onboarding: 'M02',
  emergency_contacts: 'M02',
  special_conditions_registry: 'M02',
  occupancy_traceability: 'M02',
  universal_linking: 'M02',
  packages_correspondence: 'M02',
  resident_documents: 'M02',
  read_receipts: 'M03',
  communication_analytics: 'M03',
  library_announcements: 'M03',
  community_calendar: 'M03',
  confirmation_reading: 'M03',
  surveys_polls: 'M03',
  draft_generation: 'M03',
  comment_moderation: 'M03',
  recurring_communications: 'M03',
  campaign_scheduling: 'M03',
  reactions_control: 'M03',
  digital_voting: 'M03',
  payment_agreements: 'M04',
  morosity_alerts: 'M04',
  payment_blocking: 'M04',
  portfolio_seniority: 'M04',
  auto_payment_reconciliation: 'M04',
  integrated_receivables: 'M04',
  account_statements: 'M04',
  collection_history: 'M04',
  bank_integration: 'M04',
  credit_debit_notes: 'M04',
  progressive_notifications: 'M04',
  multilevel_payments: 'M04',
  partial_payments: 'M04',
  payment_prediction: 'M04',
  payment_promises: 'M04',
  extraordinary_collection: 'M04',
  multichannel_collection: 'M04',
  payment_restrictions: 'M04',
  refinancing_simulator: 'M04',
  commission_system: 'M04',
  portfolio_board: 'M04',
  daily_collection_board: 'M04',
  cost_centers: 'M05',
  assisted_monthly_closing: 'M05',
  accounting_vouchers: 'M05',
  reconciliations: 'M05',
  accounts_payable: 'M05',
  reference_depreciation: 'M05',
  accounting_exports: 'M05',
  closing_signature: 'M05',
  erp_integration: 'M05',
  budget_comparison: 'M05',
  budget_execution: 'M05',
  accounting_traceability: 'M05',
  closing_validations: 'M05',
  resource_calendar: 'M06',
  check_in_check_out: 'M06',
  space_condition_evidence: 'M06',
  reservation_history: 'M06',
  waiting_list: 'M06',
  reservation_deposits: 'M06',
  non_use_penalties: 'M06',
  space_policies: 'M06',
  trays_by_responsible: 'M07',
  suggested_responses: 'M07',
  convivence_committee_flow: 'M07',
  complaint_patterns: 'M07',
  recurrence_indicators: 'M07',
  root_cause_analysis: 'M07',
  case_reopening: 'M07',
  escalation_rules: 'M07',
  pqrs_summary: 'M07',
  sla_configuration: 'M07',
  closure_satisfaction: 'M07',
  sla_semaphores: 'M07',
  priority_tickets: 'M07',
  internal_external_tickets: 'M07',
  services_agenda: 'M08',
  renewal_alerts: 'M08',
  asset_checklists: 'M08',
  spare_consumption: 'M08',
  accumulated_costs: 'M08',
  before_after_evidence: 'M08',
  asset_technical_data: 'M08',
  intervention_history: 'M08',
  preventive_maintenance: 'M08',
  work_orders: 'M08',
  maintenance_productivity: 'M08',
  serials_warranties: 'M08',
  maintenance_suggestions: 'M08',
  asset_location: 'M08',
  expiration_semaphores: 'M08',
  blocked_unit_alerts: 'M09',
  porteria_bitacora: 'M09',
  restricted_zone_access: 'M09',
  delivery_control: 'M09',
  ingress_evidence: 'M09',
  contractor_ingress: 'M09',
  smart_integration: 'M09',
  blacklists_alerts: 'M09',
  express_porteria_panel: 'M09',
  ingress_registry: 'M09',
  security_incidents: 'M09',
  security_board: 'M09',
  security_shifts: 'M09',
  identity_validation: 'M09',
  validation_methods: 'M09',
  frequent_visitors: 'M09',
  digital_invitations: 'M09',
  folders_by_profile: 'M10',
  document_consultation: 'M10',
  robust_version_control: 'M10',
  document_approval_flows: 'M10',
  resident_documents_mgmt: 'M10',
  document_ocr: 'M10',
  document_permissions: 'M10',
  document_templates: 'M10',
  institutional_templates: 'M10',
  document_expiration: 'M10',
  digital_signature: 'M10',
  paid_campaigns: 'M11',
  provider_comparison: 'M11',
  marketplace_commercial_dashboard: 'M11',
  provider_status: 'M11',
  provider_evaluation: 'M11',
  leads_management: 'M11',
  providers_listing: 'M11',
  segmented_offers: 'M11',
  verified_reviews: 'M11',
  quotation_requests: 'M11',
  service_traceability: 'M11',
  provider_validation: 'M11',
  dashboard_by_role: 'M12',
  pending_tasks_panel: 'M12',
  action_recommendations: 'M12',
  daily_summary: 'M12',
  configurable_widgets: 'M12',
  anomaly_analysis: 'M13',
  administrative_assistant: 'M13',
  resident_chatbot: 'M13',
  help_chatbot: 'M13',
  automatic_classification: 'M13',
  council_copilot: 'M13',
  profile_copilot: 'M13',
  pattern_detection: 'M13',
  ia_explainability: 'M13',
  draft_communications: 'M13',
  predictive_indicators: 'M13',
  contextual_responses: 'M13',
  maintenance_suggestions_ia: 'M13',
  contextual_suggestions: 'M13',
  auto_translation: 'M13',
  communications_analytics: 'M14',
  incidents_analytics: 'M14',
  occupation_analytics: 'M14',
  providers_analytics: 'M14',
  spaces_usage_analytics: 'M14',
  controlled_anonymity: 'M14',
  anomalies_analysis: 'M14',
  aperture_engagement: 'M14',
  benchmarks_between_condos: 'M14',
  historical_comparatives: 'M14',
  report_builder: 'M14',
  adoption_indicators: 'M14',
  operational_heatmap: 'M14',
  maintenance_productivity_analytics: 'M14',
  performance_ranking: 'M14',
  risk_ranking: 'M14',
  scheduled_reports: 'M14',
  advanced_segmentation: 'M14',
  financial_board: 'M14',
  interaction_traceability: 'M14',
  module_activation: 'M15',
  digital_adoption: 'M15',
  approval_rules: 'M15',
  branding_by_condo: 'M15',
  advanced_search: 'M15',
  semantic_search: 'M15',
  calendars_holidays: 'M15',
  categories_subcategories: 'M15',
  master_catalogs: 'M15',
  special_hours_config: 'M15',
  integrations_config: 'M15',
  max_quotas_user: 'M15',
  master_states: 'M15',
  access_delegations: 'M15',
  feature_flags: 'M15',
  advanced_filters: 'M15',
  excel_import: 'M15',
  metadata_taxonomies: 'M15',
  multi_language: 'M15',
  multi_currency: 'M15',
  approval_levels: 'M15',
  guided_onboarding: 'M15',
  visual_personalization: 'M15',
  preset_templates: 'M15',
  notification_policies: 'M15',
  visibility_policies: 'M15',
  configurable_rules: 'M15',
  auto_translation_config: 'M15',
  articles_videos: 'M16',
  knowledge_by_role: 'M16',
  contextual_help: 'M16',
  support_chat_tickets: 'M16',
  admin_training: 'M16',
  platform_incidents: 'M16',
  dynamic_faq: 'M16',
  support_tracking: 'M16',
  product_tours: 'M16',
  short_videos: 'M16',
};
